version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  brakeman:
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Brakeman
          command: |
            gem install brakeman
            bundle exec brakeman

workflows:
  version: 2.1
  build-and-brakeman:
    jobs:
      - build
      - brakeman
